export * from './functions/log';
export * from './functions/handle-error';
export * from "./types";
export * from "./command-handler/Command";
export * from "./command-handler/SlashCommands";
export * from "./util/Cooldowns";
export * from "./errors/NoCliCommandError";
export * from "./errors/NoCliHandlerError";
import { Client } from 'discord.js';
import CommandHandler from "./command-handler/CommandHandler";
import EventHandler from './event-handler/EventHandler';
import Cooldowns from './util/Cooldowns';
import { DebugOptions, MongoDBResult, NoCliEmojiConfigOptions, NoCliHandlerOptions, ValidationPluginsOption } from "./types";
import { log } from "./functions/log";
import handleCommandAutocomplete from './functions/handle-command-autocomplete';
import handleError from "./functions/handle-error";
import Command from './command-handler/Command';
/** The base class of nocli-handler.js */
declare class NoCliHandler {
    private _version;
    private _defaultPrefix;
    private _testServers;
    private _botOwners;
    private _disabledDefaultCommands;
    private _mongoDBConnection;
    private _showBanner;
    private _commands;
    private _commandHandler?;
    private _validations?;
    private _eventHandler?;
    private _emojiConfig;
    private _cooldowns;
    private _debugging;
    private _client;
    constructor(options: NoCliHandlerOptions);
    get client(): Client;
    get testServers(): string[];
    get botOwners(): string[];
    get disabledDefaultCommands(): string[];
    get defaultPrefix(): string;
    get debug(): DebugOptions | undefined;
    get commandHandler(): CommandHandler | undefined;
    get eventHandler(): EventHandler | undefined;
    get commands(): Map<string, Command> | undefined;
    get emojiConfig(): NoCliEmojiConfigOptions;
    get cooldowns(): Cooldowns;
    get validations(): ValidationPluginsOption | undefined;
    get mongoDBConnection(): MongoDBResult;
    private connectToMongoDB;
}
export { log, handleCommandAutocomplete, handleError };
export default NoCliHandler;
